// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dajiskxvwdutrkjwzsqu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRhamlza3h2d2R1dHJrand6c3F1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzNTIwMDAsImV4cCI6MjA2MDkyODAwMH0.k3FKZRqUpkkUeDWFcn5WFww8ha-8y-2ZtMWeSD6vy2U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);